### ISSUE TITLE
Resolution crashes when no mapping exists

### ISSUE THREAD

**Issue by kovalevvlad** [hedera-name-service/hns-resolution-sdk-legacy#2]
```typescript
import { Resolver } from "@hedera-name-service/hns-resolution-sdk";

async function xyz() {
    const resolver = new Resolver('hedera_main');
    const address = await resolver.resolveSLD("idonotexist.hbar");
    console.log(address);
}

xyz();
```
crashes with
```
Error: No Serial
    at Resolver.getAccountInfo (.../node_modules/@hedera-name-service/hns-resolution-sdk/dist/index.js:260:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Resolver.resolveSLD (.../node_modules/@hedera-name-service/hns-resolution-sdk/dist/index.js:71:40)
 ```
 ---------------------
 ```typescript
 import { Resolver } from "@hedera-name-service/hns-resolution-sdk";

async function xyz() {
    const resolver = new Resolver('hedera_main');
    const address = await resolver.resolveSLD("idonotexist");
    console.log(address);
}

xyz();
```
 crashes with
 ```
 TypeError: Cannot read properties of undefined (reading 'contractId')
    at Resolver.resolveSLD (.../node_modules/@hedera-name-service/hns-resolution-sdk/dist/index.js:66:81)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```
 
 Tested with node 18 and 21
 
 
 --------------
According to documentation:

<img width="822" alt="Screenshot 2023-10-31 at 3 28 02 PM" src="https://github.com/hedera-name-service/hns-resolution-sdk/assets/18620326/f56c56cf-09ca-4625-9990-519606c3b983">

**Comment by neru-bcw** [comment]
Thank you for bringing up your concern. When querying a domain, you would want to add the extension along with it (i.e., **.hbar**, **.cream**, and **.boo**). We will implement a patch for this edge case to further clarify it for the future.

Thanks!

**Comment by shawn-bcw** [comment]
Hi @kovalevvlad, based on your feedback, we have patched the service to include some error handling within the method, which you can then handle within a `try/catch`.

Please find the update package [here](https://www.npmjs.com/package/@hedera-name-service/hns-resolution-sdk/v/2.0.11) and a link to the error response for the method you have specified [here](https://github.com/hedera-name-service/hns-resolution-sdk?tab=readme-ov-file#errors).

If you have any issues, please create them in the new repository. Thank you.
