### ISSUE TITLE
getAllDomainsForAccount() Hangs

### ISSUE THREAD

**Issue by jwtong** [hedera-name-service/hns-resolution-sdk-legacy#5]
I have a _hedera_main_ resolver that successfully can get address from domain via `resolver.resolveSLD`. On the inverse of `getAllDomainsForAccount()`, it hangs forever.

**Comment by neru-bcw** [comment]
Hi, 

Thanks for reaching out, is possible to get the inputs you are attempting? 

Thanks!

**Comment by shawn-bcw** [comment]
Hi @jwtong, we have patched the service to include some error handling within the method, which you can then handle within a `try/catch`.

Please find the update package [here](https://www.npmjs.com/package/@hedera-name-service/hns-resolution-sdk/v/2.0.11) and a link to the updated docs [here](https://github.com/hedera-name-service/hns-resolution-sdk).

If you have any issues, please create them in the new repository. Thank you.
